language: python
python:
  # Picard currently supports Python >=2.6 and <3
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
cache:
  - apt
  - $HOME/.pip/cache
env:
  global:
    - PIP_INSTALL="pip install --download-cache='$HOME/.pip/cache'"
  matrix:
    - DISCID=""
    - DISCID="$PIP_INSTALL python-libdiscid"
    - DISCID="$PIP_INSTALL discid"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-qt4
  - sudo apt-get install -qq libdiscid0
install:
  # Install dependencies
  - $PIP_INSTALL 'Mutagen>=1.20'
  - $DISCID
  # Set up Picard
  - python setup.py build_ext -i
  - python setup.py build_locales -i
# Run the tests!
script: "python setup.py test"
