os: linux
dist: trusty
language: python
python: "3.6"
cache:
  - apt
  - pip
env:
  global:
    - PIP_INSTALL="pip install"
  matrix:
    - DISCID="$PIP_INSTALL discid" MUTAGEN="$PIP_INSTALL mutagen>=1.37"
before_install:
  - sudo apt-get update -qq && sudo apt-get install -qq libdiscid0 libdiscid0-dev qt5-default
  - $PIP_INSTALL sip
  - $PIP_INSTALL pyqt5
  - $MUTAGEN
  - $DISCID
install:
  # Set up Picard
  - python setup.py build_ext -i
  - python setup.py build_locales -i
# Run the tests!
script: "python setup.py test"

# Tell people that tests were run
notifications:
  irc: "chat.freenode.net#metabrainz"